from PyQt5 import QtCore, QtGui, QtWidgets
import image

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(578, 544)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.send_Button = QtWidgets.QPushButton(self.centralwidget)
        self.send_Button.setGeometry(QtCore.QRect(90, 330, 88, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.send_Button.setFont(font)
        self.send_Button.setObjectName("send_Button")
        self.send_Text = QtWidgets.QTextEdit(self.centralwidget)
        self.send_Text.setGeometry(QtCore.QRect(190, 330, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.send_Text.setFont(font)
        self.send_Text.setObjectName("send_Text")
        self.baud_text = QtWidgets.QLabel(self.centralwidget)
        self.baud_text.setGeometry(QtCore.QRect(160, 380, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.baud_text.setFont(font)
        self.baud_text.setObjectName("baud_text")
        self.port_text = QtWidgets.QLabel(self.centralwidget)
        self.port_text.setGeometry(QtCore.QRect(310, 380, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.port_text.setFont(font)
        self.port_text.setObjectName("port_text")
        self.clear_Button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_Button.setGeometry(QtCore.QRect(40, 260, 88, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.clear_Button.setFont(font)
        self.clear_Button.setObjectName("clear_Button")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(40, 120, 521, 131))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.port_List = QtWidgets.QComboBox(self.centralwidget)
        self.port_List.setGeometry(QtCore.QRect(310, 410, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.port_List.setFont(font)
        self.port_List.setObjectName("port_List")
        self.baud_List = QtWidgets.QComboBox(self.centralwidget)
        self.baud_List.setGeometry(QtCore.QRect(160, 410, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.baud_List.setFont(font)
        self.baud_List.setObjectName("baud_List")
        self.connect_Button = QtWidgets.QPushButton(self.centralwidget)
        self.connect_Button.setGeometry(QtCore.QRect(60, 410, 93, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.connect_Button.setFont(font)
        self.connect_Button.setStyleSheet("#connect_Button:checked{\n"
"background-color: rgb(0, 255, 127);\n"
"}")
        self.connect_Button.setCheckable(True)
        self.connect_Button.setObjectName("connect_Button")
        self.update_Button = QtWidgets.QPushButton(self.centralwidget)
        self.update_Button.setGeometry(QtCore.QRect(440, 410, 93, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.update_Button.setFont(font)
        self.update_Button.setObjectName("update_Button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 10, 401, 91))
        self.label.setStyleSheet("image: url(:/myImage/logo.png)")
        self.label.setText("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 578, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.send_Button.setText(_translate("MainWindow", "Send"))
        self.baud_text.setText(_translate("MainWindow", "Baud"))
        self.port_text.setText(_translate("MainWindow", "Port"))
        self.clear_Button.setText(_translate("MainWindow", "Clear"))
        self.connect_Button.setText(_translate("MainWindow", "Connect"))
        self.update_Button.setText(_translate("MainWindow", "Update"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())